apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-app-deployment
  labels:
    app: review-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-app
  template:
    metadata:
      labels:
        app: review-app
    spec:
      containers:
      - name: review-app
        image: mozdockerregistry.azurecr.io/mozammiljenkins
        ports:
        - containerPort: 8000
